import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

const baseURL = process.env.VERCEL_URL || "http://localhost:3001";

export async function getServerSideProps() {
  try {
    const url = `${baseURL}/api/test/?type=users&offset=0&size=10`;
    const requestHeaders = new Headers();
    requestHeaders.set("Content-Type", "application/json");
    const response = await fetch(url, {
      headers: requestHeaders,
    });
    if (!response.ok) {
      throw { message: response.statusText, status: response.status };
    }
    const data = await response.json();
    return {
      props: { ...data },
    };
  } catch (e) {
    console.log("Fetch error happened", e);
    return { props: { type: null } };
  }
}

export default function Home(props) {
  console.log("Props received", props);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>Just a test(see console)</main>
    </>
  );
}
